### PR TITLE
Doc: improve examples

### PR DESCRIPTION
**Pull request by ArthurClemens**

### CODE REVIEW

**Comment by zachdaniel** [comment]
Why change the name of the module?

**Comment by ArthurClemens** [comment]
A module name ending with "Live" will be closer to other module names in a LiveView application. Example names from the official docs: `MyAppWeb.ThermostatLive`, `DemoWeb.ClockLive`.

**Comment by zachdaniel** [comment]
Yes, but those are live views which are supposed to end in `Live` per phoenix conventions. On mount hooks I'm not sure if they should follow that convention (because then they look like live views)

**Comment by zachdaniel** [comment]
But if there is phoenix convention for that we should follow it 👍

**Comment by ArthurClemens** [comment]
Hmm, not sure myself. I'll revert that filename change.

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
