### PR TITLE
feat: change `ash_authentication_live_session` to use `assign_new`

### PR DESCRIPTION
**Pull request by vonagam**
This is a breaking change.

LiveView module provides [`assign_new`](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#assign_new/3) method. It allows sharing set assigned values between plugs, dead, live and nested mounts. The method can be used (as it was designed for cases like) in `AshAuthentication.Phoenix.LiveSession.on_mount` to set "current_" assigns.

But `assign_new` cannot skip setting value. So current behavior for when `subject_to_user` does not success and nothing is set cannot be replicated. If there were no user found "current_thing" will be set to `nil`.

Another change is that iteration happens not on session entries but on authorization resources. It means that "current_user" assign is always set to nil or to a found record. So the problem listed in documentation is solved:
> There are two problems with the above, however.
> 1) If there is no user present, it will not set `current_user: nil`.

I'm okay with this PR being closed, no pressure, just interested to know if there are any specific downsides to this approach that I am maybe missing.

### CODE REVIEW

**Comment by jimsynz** [comment]
I like this approach, the only thing I worry about is what is the implication of `assign_new` not setting the value if the key is already present?  Is it possible that there could already be a `current_X` set to `nil` in the socket?  Should we always blindly overwrite it by using `assign`?

**Comment by vonagam** [comment]
Yes, if something sets `current_X` (with `assign` or `assing_new`) to some value (nil or some record) before the hook then `assign_new` will skip doing lookup of its own.

Is there any use case where you want to set `current_X` to something and then still want the hook to overwrite it?

**Comment by jimsynz** [comment]
> Is there any use case where somebody wants to set `current_X` to something and then still want the hook to overwrite it?

Yeah, I don't think anyone is _likely_ to want that behaviour. I  just want to make sure we have the least surprising semantics by default.

**Comment by jimsynz** [comment]
Any opinions @zachdaniel?

**Comment by zachdaniel** [comment]
Whoops, meant to respond to this sooner :) I think we should raise if its already set, and then use `assign_new` to set it, yes. That also eliminates some logic we have to do in an on mount hook to set the user key to `nil` if its not present.

**Comment by vonagam** [comment]
Here is a variant with the raise. 

For record, `AshAuthentication.Phoenix.LiveSession` is always the first `on_mount` hook if `ash_authentication_live_session` is used. So only if somebody used the default hook manually they could have set `current_subject` assign before it. Personally I find it more like a feature than a bug - allows one to customize the behavior and prevent/replace/skip the default lookup if certain conditions are met - but I myself don't have a use for such thing so ok forbidding it if that is considered ambiguous.

**Review by zachdaniel — APPROVED** [review]

**Comment by jimsynz** [comment]
Thanks for the contribution!!

**Pull request merged**
