### PR TITLE
Updates documentation to nest in the resources folder

### PR DESCRIPTION
**Pull request by britton-jb**
The only piece I'm not clear on with this one is the change on the identity from `unique_email` to `email`, as there seems like there is a bit of inconsistency on that one in the docs.

### CODE REVIEW

**Comment by jimsynz** [comment]
This is great work thanks!

I personally think identities should be explicitly named because it can be a little opaque as to what an identity actually is otherwise (not the best name in town) - but I'll defer to whatever @zachdaniel's reckons are.

**Comment by zachdaniel** [comment]
Agreed. The name is arbitrary, but being expressive is better.

**Comment by britton-jb** [comment]
Updated across the file.

**Review by jimsynz — APPROVED** [review]
shuffle

**Pull request merged**
