### PR TITLE
dynamic router - some additional tests, fixes and failures

### PR DESCRIPTION
**Pull request by ahacking**
# Additional tests, fixes and failures

The following PR can be raided for the following:
* Additional scoped router tests including nested routes and use of ```:unscoped``` paths
* Fixes to support more than one sign_in_route or reset_route helper due to live session name clash (using ```:as``` prefix).

## Working controller tests

Checking the controller mounts and renders both connected and unconnected mounts.

```$
mix test --exclude failing
```

## Broken controller tests

Register and sign-in tests seem to fail due to the dynamic router dropping the params along the way. Note the original query string does contain the token.

```$
mix test --include failing

  1) test AshAuthentication Controller register user (AshAuthentication.Phoenix.ControllerTest)
     test/controller_test.exs:37
     Expected truthy, got nil
     code: assert get_session(conn, :user_token)
     arguments:

         # 1
         %Plug.Conn{
           adapter: {Plug.Adapters.Test.Conn, :...},
           assigns: %{
             flash: %{},
             current_user: nil,
             failure_reason: %AshAuthentication.Errors.AuthenticationFailed{
               caused_by: %{
                 message: "Invalid Error\n\n* argument token is required\n  (elixir 1.15.4) lib/process.ex:860: Process.info/2\n  (ash 3.3.3) lib/ash/error/query/required.ex:5: Ash.Error.Query.Required.exception/1\n  (ash 3.3.3) lib/ash/query/query.ex:613: anonymous fn/2 in Ash.Query.require_arguments/2\n  (elixir 1.15.4) lib/enum.ex:2510: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n  (ash 3.3.3) lib/ash/query/query.ex:551: Ash.Query.for_read/4\n  (ash_authentication 4.0.2) lib/ash_authentication/strategies/password/actions.ex:113: AshAuthentication.Strategy.Password.Actions.sign_in_with_token/3\n  (ash_authentication 4.0.2) lib/ash_authentication/strategies/password/plug.ex:37: AshAuthentication.Strategy.Password.Plug.sign_in_with_token/2\n  (ash_authentication 4.0.2) lib/ash_authentication/plug/dispatcher.ex:29: AshAuthentication.Plug.Dispatcher.call/2\n  (phoenix 1.7.14) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2\n  (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5\n  (ash_authentication_phoenix 2.0.2) test/support/phoenix.ex:106: AshAuthentication.Phoenix.Test.Endpoint.plug_builder_call/2\n  (ash_authentication_phoenix 2.0.2) deps/plug/lib/plug/debugger.ex:136: AshAuthentication.Phoenix.Test.Endpoint.\"call (overridable 3)\"/2\n  (ash_authentication_phoenix 2.0.2) test/support/phoenix.ex:106: AshAuthentication.Phoenix.Test.Endpoint.call/2\n  (phoenix 1.7.14) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5\n  test/controller_test.exs:52: AshAuthentication.Phoenix.ControllerTest.\"test AshAuthentication Controller register user\"/1\n  (ex_unit 1.15.4) lib/ex_unit/runner.ex:463: ExUnit.Runner.exec_test/2\n  (stdlib 5.0.2) timer.erl:270: :timer.tc/2\n  (ex_unit 1.15.4) lib/ex_unit/runner.ex:385: anonymous fn/5 in ExUnit.Runner.spawn_test_monitor/4",
                 module: AshAuthentication.Strategy.Password.Actions,
                 strategy: %AshAuthentication.Strategy.Password{
                   confirmation_required?: true,
                   hash_provider: AshAuthentication.BcryptProvider,
                   hashed_password_field: :hashed_password,
                   identity_field: :email,
                   name: :password,
                   password_confirmation_field: :password_confirmation,
                   password_field: :password,
                   provider: :password,
                   register_action_accept: [],
                   register_action_name: :register_with_password,
                   registration_enabled?: true,
                   resettable: %AshAuthentication.Strategy.Password.Resettable{
                     token_lifetime: {3, :days},
                     request_password_reset_action_name: :request_password_reset_with_password,
                     password_reset_action_name: :password_reset_with_password,
                     sender: {AshAuthentication.SenderFunction, [fun: &Example.Accounts.User.sender_0_generated_544C47D3F68D0B0560940CFE0150BE20/3]}
                   },
                   resource: Example.Accounts.User,
                   sign_in_action_name: :sign_in_with_password,
                   sign_in_enabled?: true,
                   sign_in_token_lifetime: {60, :seconds},
                   sign_in_tokens_enabled?: true,
                   sign_in_with_token_action_name: :sign_in_with_token_for_password,
                   strategy_module: AshAuthentication.Strategy.Password
                 },
                 action: :sign_in_with_token_for_password
               },
               changeset: nil,
               field: nil,
               query: nil,
               strategy: %AshAuthentication.Strategy.Password{
                 confirmation_required?: true,
                 hash_provider: AshAuthentication.BcryptProvider,
                 hashed_password_field: :hashed_password,
                 identity_field: :email,
                 name: :password,
                 password_confirmation_field: :password_confirmation,
                 password_field: :password,
                 provider: :password,
                 register_action_accept: [],
                 register_action_name: :register_with_password,
                 registration_enabled?: true,
                 resettable: %AshAuthentication.Strategy.Password.Resettable{
                   token_lifetime: {3, :days},
                   request_password_reset_action_name: :request_password_reset_with_password,
                   password_reset_action_name: :password_reset_with_password,
                   sender: {AshAuthentication.SenderFunction, [fun: &Example.Accounts.User.sender_0_generated_544C47D3F68D0B0560940CFE0150BE20/3]}
                 },
                 resource: Example.Accounts.User,
                 sign_in_action_name: :sign_in_with_password,
                 sign_in_enabled?: true,
                 sign_in_token_lifetime: {60, :seconds},
                 sign_in_tokens_enabled?: true,
                 sign_in_with_token_action_name: :sign_in_with_token_for_password,
                 strategy_module: AshAuthentication.Strategy.Password
               },
               splode: nil,
               bread_crumbs: [],
               vars: [],
               path: [],
               stacktrace: #Splode.Stacktrace<>,
               class: :forbidden
             }
           },
           body_params: %Plug.Conn.Unfetched{aspect: :body_params},
           cookies: %{},
           halted: false,
           host: "www.example.com",
           method: "GET",
           owner: #PID<0.445.0>,
           params: %{},
           path_info: ["auth", "user", "password", "sign_in_with_token"],
           path_params: %{},
           port: 80,
           private: %{
             :strategy => %AshAuthentication.Strategy.Password{
               confirmation_required?: true,
               hash_provider: AshAuthentication.BcryptProvider,
               hashed_password_field: :hashed_password,
               identity_field: :email,
               name: :password,
               password_confirmation_field: :password_confirmation,
               password_field: :password,
               provider: :password,
               register_action_accept: [],
               register_action_name: :register_with_password,
               registration_enabled?: true,
               resettable: %AshAuthentication.Strategy.Password.Resettable{
                 token_lifetime: {3, :days},
                 request_password_reset_action_name: :request_password_reset_with_password,
                 password_reset_action_name: :password_reset_with_password,
                 sender: {AshAuthentication.SenderFunction, [fun: &Example.Accounts.User.sender_0_generated_544C47D3F68D0B0560940CFE0150BE20/3]}
               },
               resource: Example.Accounts.User,
               sign_in_action_name: :sign_in_with_password,
               sign_in_enabled?: true,
               sign_in_token_lifetime: {60, :seconds},
               sign_in_tokens_enabled?: true,
               sign_in_with_token_action_name: :sign_in_with_token_for_password,
               strategy_module: AshAuthentication.Strategy.Password
             },
             :phoenix_view => %{_: AshAuthentication.Phoenix.Test.AuthView},
             AshAuthentication.Phoenix.Test.Router => [],
             :phoenix_endpoint => AshAuthentication.Phoenix.Test.Endpoint,
             :plug_skip_csrf_protection => true,
             :phoenix_recycled => false,
             :phoenix_router => AshAuthentication.Phoenix.Test.Router,
             :plug_session_fetch => :done,
             :plug_session => %{},
             :before_send => [#Function<0.71811376/1 in Plug.CSRFProtection.call/2>, #Function<4.43949669/1 in Phoenix.Controller.fetch_flash/2>,
              #Function<0.76384852/1 in Plug.Session.before_send/2>],
             :phoenix_action => :failure,
             :phoenix_layout => %{_: {DevWeb.LayoutView, :app}},
             :phoenix_controller => AshAuthentication.Phoenix.Test.AuthController,
             :phoenix_format => "html",
             :authentication_result => {:error,
              %AshAuthentication.Errors.AuthenticationFailed{
                caused_by: %{
                  message: "Invalid Error\n\n* argument token is required\n  (elixir 1.15.4) lib/process.ex:860: Process.info/2\n  (ash 3.3.3) lib/ash/error/query/required.ex:5: Ash.Error.Query.Required.exception/1\n  (ash 3.3.3) lib/ash/query/query.ex:613: anonymous fn/2 in Ash.Query.require_arguments/2\n  (elixir 1.15.4) lib/enum.ex:2510: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n  (ash 3.3.3) lib/ash/query/query.ex:551: Ash.Query.for_read/4\n  (ash_authentication 4.0.2) lib/ash_authentication/strategies/password/actions.ex:113: AshAuthentication.Strategy.Password.Actions.sign_in_with_token/3\n  (ash_authentication 4.0.2) lib/ash_authentication/strategies/password/plug.ex:37: AshAuthentication.Strategy.Password.Plug.sign_in_with_token/2\n  (ash_authentication 4.0.2) lib/ash_authentication/plug/dispatcher.ex:29: AshAuthentication.Plug.Dispatcher.call/2\n  (phoenix 1.7.14) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2\n  (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5\n  (ash_authentication_phoenix 2.0.2) test/support/phoenix.ex:106: AshAuthentication.Phoenix.Test.Endpoint.plug_builder_call/2\n  (ash_authentication_phoenix 2.0.2) deps/plug/lib/plug/debugger.ex:136: AshAuthentication.Phoenix.Test.Endpoint.\"call (overridable 3)\"/2\n  (ash_authentication_phoenix 2.0.2) test/support/phoenix.ex:106: AshAuthentication.Phoenix.Test.Endpoint.call/2\n  (phoenix 1.7.14) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5\n  test/controller_test.exs:52: AshAuthentication.Phoenix.ControllerTest.\"test AshAuthentication Controller register user\"/1\n  (ex_unit 1.15.4) lib/ex_unit/runner.ex:463: ExUnit.Runner.exec_test/2\n  (stdlib 5.0.2) timer.erl:270: :timer.tc/2\n  (ex_unit 1.15.4) lib/ex_unit/runner.ex:385: anonymous fn/5 in ExUnit.Runner.spawn_test_monitor/4",
                  module: AshAuthentication.Strategy.Password.Actions,
                  strategy: %AshAuthentication.Strategy.Password{
                    confirmation_required?: true,
                    hash_provider: AshAuthentication.BcryptProvider,
                    hashed_password_field: :hashed_password,
                    identity_field: :email,
                    name: :password,
                    password_confirmation_field: :password_confirmation,
                    password_field: :password,
                    provider: :password,
                    register_action_accept: [],
                    register_action_name: :register_with_password,
                    registration_enabled?: true,
                    resettable: %AshAuthentication.Strategy.Password.Resettable{
                      token_lifetime: {3, :days},
                      request_password_reset_action_name: :request_password_reset_with_password,
                      password_reset_action_name: :password_reset_with_password,
                      sender: {...}
                    },
                    resource: Example.Accounts.User,
                    sign_in_action_name: :sign_in_with_password,
                    sign_in_enabled?: true,
                    sign_in_token_lifetime: {...},
                    ...
                  },
                  action: :sign_in_with_token_for_password
                },
                changeset: nil,
                field: nil,
                query: nil,
                strategy: %AshAuthentication.Strategy.Password{
                  confirmation_required?: true,
                  hash_provider: AshAuthentication.BcryptProvider,
                  hashed_password_field: :hashed_password,
                  identity_field: :email,
                  name: :password,
                  password_confirmation_field: :password_confirmation,
                  password_field: :password,
                  provider: :password,
                  register_action_accept: [],
                  register_action_name: :register_with_password,
                  registration_enabled?: true,
                  resettable: %AshAuthentication.Strategy.Password.Resettable{
                    token_lifetime: {3, :days},
                    request_password_reset_action_name: :request_password_reset_with_password,
                    password_reset_action_name: :password_reset_with_password,
                    ...
                  },
                  resource: Example.Accounts.User,
                  sign_in_action_name: :sign_in_with_password,
                  sign_in_enabled?: true,
                  ...
                },
                splode: nil,
                bread_crumbs: [],
                vars: [],
                path: [],
                stacktrace: #Splode.Stacktrace<>,
                class: :forbidden
              }},
             :failure_args => [
               {:password, :sign_in_with_token},
               %AshAuthentication.Errors.AuthenticationFailed{
                 caused_by: %{
                   message: "Invalid Error\n\n* argument token is required\n  (elixir 1.15.4) lib/process.ex:860: Process.info/2\n  (ash 3.3.3) lib/ash/error/query/required.ex:5: Ash.Error.Query.Required.exception/1\n  (ash 3.3.3) lib/ash/query/query.ex:613: anonymous fn/2 in Ash.Query.require_arguments/2\n  (elixir 1.15.4) lib/enum.ex:2510: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n  (ash 3.3.3) lib/ash/query/query.ex:551: Ash.Query.for_read/4\n  (ash_authentication 4.0.2) lib/ash_authentication/strategies/password/actions.ex:113: AshAuthentication.Strategy.Password.Actions.sign_in_with_token/3\n  (ash_authentication 4.0.2) lib/ash_authentication/strategies/password/plug.ex:37: AshAuthentication.Strategy.Password.Plug.sign_in_with_token/2\n  (ash_authentication 4.0.2) lib/ash_authentication/plug/dispatcher.ex:29: AshAuthentication.Plug.Dispatcher.call/2\n  (phoenix 1.7.14) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2\n  (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5\n  (ash_authentication_phoenix 2.0.2) test/support/phoenix.ex:106: AshAuthentication.Phoenix.Test.Endpoint.plug_builder_call/2\n  (ash_authentication_phoenix 2.0.2) deps/plug/lib/plug/debugger.ex:136: AshAuthentication.Phoenix.Test.Endpoint.\"call (overridable 3)\"/2\n  (ash_authentication_phoenix 2.0.2) test/support/phoenix.ex:106: AshAuthentication.Phoenix.Test.Endpoint.call/2\n  (phoenix 1.7.14) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5\n  test/controller_test.exs:52: AshAuthentication.Phoenix.ControllerTest.\"test AshAuthentication Controller register user\"/1\n  (ex_unit 1.15.4) lib/ex_unit/runner.ex:463: ExUnit.Runner.exec_test/2\n  (stdlib 5.0.2) timer.erl:270: :timer.tc/2\n  (ex_unit 1.15.4) lib/ex_unit/runner.ex:385: anonymous fn/5 in ExUnit.Runner.spawn_test_monitor/4",
                   module: AshAuthentication.Strategy.Password.Actions,
                   strategy: %AshAuthentication.Strategy.Password{
                     confirmation_required?: true,
                     hash_provider: AshAuthentication.BcryptProvider,
                     hashed_password_field: :hashed_password,
                     identity_field: :email,
                     name: :password,
                     password_confirmation_field: :password_confirmation,
                     password_field: :password,
                     provider: :password,
                     register_action_accept: [],
                     register_action_name: :register_with_password,
                     registration_enabled?: true,
                     resettable: %AshAuthentication.Strategy.Password.Resettable{
                       token_lifetime: {3, :days},
                       request_password_reset_action_name: :request_password_reset_with_password,
                       password_reset_action_name: :password_reset_with_password,
                       ...
                     },
                     resource: Example.Accounts.User,
                     sign_in_action_name: :sign_in_with_password,
                     sign_in_enabled?: true,
                     ...
                   },
                   action: :sign_in_with_token_for_password
                 },
                 changeset: nil,
                 field: nil,
                 query: nil,
                 strategy: %AshAuthentication.Strategy.Password{
                   confirmation_required?: true,
                   hash_provider: AshAuthentication.BcryptProvider,
                   hashed_password_field: :hashed_password,
                   identity_field: :email,
                   name: :password,
                   password_confirmation_field: :password_confirmation,
                   password_field: :password,
                   provider: :password,
                   register_action_accept: [],
                   register_action_name: :register_with_password,
                   registration_enabled?: true,
                   resettable: %AshAuthentication.Strategy.Password.Resettable{
                     token_lifetime: {3, ...},
                     request_password_reset_action_name: :request_password_reset_with_password,
                     ...
                   },
                   resource: Example.Accounts.User,
                   sign_in_action_name: :sign_in_with_password,
                   ...
                 },
                 splode: nil,
                 bread_crumbs: [],
                 vars: [],
                 path: [],
                 stacktrace: #Splode.Stacktrace<>,
                 class: :forbidden
               }
             ]
           },
           query_params: %Plug.Conn.Unfetched{aspect: :query_params},
           query_string: "token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ-PiA0LjAiLCJleHAiOjE3MjQ1Nzg2MzAsImlhdCI6MTcyMzM2OTAzMCwiaXNzIjoiQXNoQXV0aGVudGljYXRpb24gdjQuMC4yIiwianRpIjoiMnZsYTYwNGpxNGFpMDh2NGprMDAwMDQxIiwibmJmIjoxNzIzMzY5MDMwLCJwdXJwb3NlIjoic2lnbl9pbiIsInN1YiI6InVzZXI_aWQ9M2Q5MThlZDUtNjI0Zi00NjU1LWFmMmEtYmI1Njk0YjNmNGU5In0.rxuDrhFbTnMjMVjrpN3Or_yWqSZIhUpPJnNcHBUW_F8",
           remote_ip: {127, 0, 0, 1},
           req_cookies: %{},
           req_headers: [],
           request_path: "/auth/user/password/sign_in_with_token",
           resp_body: "<html><body>You are being <a href=\"/sign-in\">redirected</a>.</body></html>",
           resp_cookies: %{},
           resp_headers: [
             {"content-type", "text/html; charset=utf-8"},
             {"cache-control", "max-age=0, private, must-revalidate"},
             {"referrer-policy", "strict-origin-when-cross-origin"},
             {"x-content-type-options", "nosniff"},
             {"x-download-options", "noopen"},
             {"x-frame-options", "SAMEORIGIN"},
             {"x-permitted-cross-domain-policies", "none"},
             {"location", "/sign-in"}
           ],
           scheme: :http,
           script_name: [],
           secret_key_base: :...,
           state: :sent,
           status: 302
         }

         # 2
         :user_token

     stacktrace:
       test/controller_test.exs:54: (test)
```

### CODE REVIEW

**Comment by zachdaniel** [comment]
Lets update the docs to show that you can use `{:unscoped, ...}` for the `auth_routes_prefix` (and also for the other routes now that I think of it).

I'll look at the failing tests.

**Comment by zachdaniel** [comment]
Okay, so I *think* that this may be something we have to do because our test set up is atypical or something, because this definitely wasn't necessary in a real app where I'm using this. But it can't hurt to add it.

I believe we just need to put
```elixir
    # ensure query params have been fetched
    conn = Plug.Conn.fetch_query_params(conn)
```

at the top of the strategy router. It won't do any work if the query params have already been fetched, so its safe to do in general.

**Comment by zachdaniel** [comment]
I noticed there are still failing tests there, but in at least one of those tests I believe you just need to register a user before testing sign in, etc. This looks great BTW ❤️. Excited to get it merged.

**Comment by ahacking** [comment]
Thanks for the input, I will look to get this firmed up and ready to merge within the next day.

**Comment by ahacking** [comment]
@zachdaniel I have addressed your feedback and have working controller tests.

**Comment by zachdaniel** [comment]
I wonder why CI isn't showing results here

**Comment by zachdaniel** [comment]
Oh, because of the branch target. @ahacking we merged the dynamic router, can you reopen this PR against `main`?

**Comment by ahacking** [comment]
I think we may have some overlap in the controller tests.

**Comment by zachdaniel** [comment]
Yours are likely more comprehensive :)

**Comment by ahacking** [comment]
@zachdaniel is there anything else required before this can be merged?

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
